### ISSUE TITLE
Wyko ".opd" file Compatibility

### ISSUE THREAD

**Issue by VadanKhan** [fredericjs/surfalize#14]
Is it possible if you could add information on which Wyko Tools .opd files are compatible? Even better if older tools are supported!
I can confirm that reading the test_1.opd indeed works, but I am using the Wyko HD9800 (old tool) and I get errors when I try to load these files:

`Error reading C:\Users\***\Documents\WYKO_DATA\***\row1column1.fc.opd: 'Date' `

[row1column1.fc.zip](https://github.com/user-attachments/files/17391698/row1column1.fc.zip)

I would really appreciate being able to use this package for .opd files if possible!

**Comment by fredericjs** [comment]
Unfortunately I have no idea what devices this is compatible with since I myself do not use OPD files. I only implemented the format based on isssue #3 and what info was provided there.

I will look into your file and see what difference there is.

**Comment by fredericjs** [comment]
Found the issue, your file format is essentially the same, there is just no date information in the metadata. Since my implementation assumed there would be date info present, it throws an error there. I will update the package with a bugfix release.

That is what your file looks like for me. Is that correct? The 1e37 lets me assume there is still something going wrong here...
![grafik](https://github.com/user-attachments/assets/913fc301-45c5-40ea-a0b9-e5507abf78ea)

**Comment by fredericjs** [comment]
The bug has been fixed with 0.13.1 now available on PyPi. For the time being, you will have to set the outlier values to nan yourself since I am not sure how they encode the outlier values. You are using 1e10 as the threshold but I don't think that is generally applicable to all files.
